# Generated by Django 4.2.1 on 2023-05-10 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AllProduct",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("price", models.CharField(max_length=100)),
                ("detail", models.TextField(blank=True, null=True)),
                ("imageurl", models.CharField(blank=True, max_length=200, null=True)),
                ("instock", models.BooleanField(default=True)),
                ("quantity", models.IntegerField(default=1)),
                ("unit", models.CharField(default="-", max_length=200)),
                (
                    "images",
                    models.ImageField(blank=True, null=True, upload_to="products"),
                ),
            ],
        ),
    ]
