# Generated by Django 4.2.1 on 2023-05-10 08:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("app_uncle_shop", "0002_profile"),
    ]

    operations = [
        migrations.CreateModel(
            name="OrderProduct",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order_id", models.CharField(max_length=100)),
                ("product_id", models.CharField(max_length=100)),
                ("product_name", models.CharField(max_length=100)),
                ("price", models.IntegerField()),
                ("quantity", models.IntegerField()),
                ("total", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="OrderPending",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order_id", models.CharField(max_length=100)),
                ("name", models.CharField(max_length=100)),
                ("tel", models.CharField(max_length=100)),
                ("address", models.TextField()),
                ("shipping", models.CharField(max_length=100)),
                ("payment", models.CharField(max_length=100)),
                ("other", models.TextField(blank=True, null=True)),
                ("stamp", models.DateTimeField(auto_now_add=True, null=True)),
                ("paid", models.BooleanField(default=False)),
                ("slip", models.ImageField(blank=True, null=True, upload_to="slip")),
                ("slip_time", models.DateField(blank=True, null=True)),
                (
                    "bank_account",
                    models.CharField(
                        choices=[
                            ("KBank", "KBank"),
                            ("SCB", "SCB"),
                            ("TTB", "TTB"),
                            ("KTB", "KTB"),
                            ("BBL", "BBL"),
                            ("BAY", "BAY"),
                            ("BAY", "BAY"),
                            ("อื่นๆ", "อื่นๆ"),
                        ],
                        default="KBank",
                        max_length=50,
                    ),
                ),
                ("paymentid", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "tracking_number",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Cart",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("product_id", models.CharField(max_length=100)),
                ("product_name", models.CharField(max_length=100)),
                ("price", models.IntegerField()),
                ("quantity", models.IntegerField()),
                ("stamp", models.DateTimeField(auto_now_add=True, null=True)),
                ("total", models.IntegerField()),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
