# Generated by Django 4.2.1 on 2023-05-15 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app_uncle_shop", "0004_alter_orderpending_bank_account"),
    ]

    operations = [
        migrations.RenameField(
            model_name="cart", old_name="product_id", new_name="productid",
        ),
        migrations.RenameField(
            model_name="cart", old_name="product_name", new_name="productname",
        ),
        migrations.RenameField(
            model_name="profile", old_name="cart_quantity", new_name="cartquan",
        ),
        migrations.RenameField(
            model_name="profile", old_name="user_type", new_name="usertype",
        ),
    ]
