# Generated by Django 4.2.1 on 2023-05-29 14:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app_uncle_shop", "0008_verifyemail"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category_name",
                    models.CharField(default="ສິນຄ້າທົ່ວໄປ", max_length=250),
                ),
                ("detail", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name="allproduct",
            name="category_name",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="app_uncle_shop.category",
            ),
        ),
    ]
