# Generated by Django 4.2.1 on 2023-05-29 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_uncle_shop", "0009_category_allproduct_category_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="category_name",
            field=models.CharField(default="สินค้าทั่วไป", max_length=250),
        ),
    ]
